version: '3.8'

services:
  subtitles-api:
    image: ${DOCKER_IMAGE:-ghcr.io/serhw/english-subtitels-api:latest}
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      # Override Seq URL via environment variables
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
      # You can also override log levels
      - Serilog__MinimumLevel__Default=Information
    secrets:
      - db_connection_string
    depends_on:
      - seq
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    volumes:
      # Named volume for Serilog buffering
      - serilog-buffer:/tmp/serilog-buffer

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=QFu74F0HozBXBGahJyG8YYM7mgZU+c2PdbfTMbn4tqGxiGM6mLQUiZfdXBWFOO5438iXtkMqmIavZ7ZUYPomgx1FILpeB8SHh7bBW4vxjOE9
      # Generate hash with: echo 'your-password' | docker run --rm -i datalust/seq config hash
    ports:
      - "5341:5341"
    volumes:
      - seq-data:/data
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: overlay
    attachable: true

volumes:
  seq-data:
  serilog-buffer:

secrets:
  db_connection_string:
    external: true
    name: subtitles_db_connection
